name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/hackathon-frontend:latest .
          docker push   ${{ secrets.ECR_REGISTRY }}/hackathon-frontend:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE_FRONTEND }} \
            --force-new-deployment
          echo "ECS frontend deploy finished"
