name: Build & Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build & Push Docker image
        run: |
          # Dockerfile이 올바르게 수정되어 'npm run buildy'를 통해 앱을 빌드합니다.
          docker build -t ${{ secrets.ECR_REGISTRY }}/hackathon-frontend:latest .
          docker push ${{ secrets.ECR_REGISTRY }}/hackathon-frontend:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster hackathon-cluster \
            --service frontend-service \
            --region ${{ secrets.AWS_REGION }} \
            --force-new-deployment
          echo "ECS frontend deploy finished"
